# Site settings
title: EmacSide
email: hi@emacside.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring the IDE side of Emacs. Common use cases
  and popular tasks among IDEs performed with Emacs.
baseurl: ""
url: "http://emacside.com"
twitter_username: emacside
github_username:  marcanuy/emacside.com

# Outputting
permalink: /:categories/:title

# Build settings
markdown: kramdown

disqus_id: emacside

tag:
  page:
    dir: tag
    title: "%s features in Emacs"
    header: "%s features in Emacs"
    description: "How to do some of the %s tricks in Emacs"
    metadesc: "%s tasks equivalents in Emacs"
  index:
    dir: tags
    title: ""
    header: ""
    description: ""
    metadesc_format: ""

collections:
  articles:
    output: true
    permalink: /:path/
  editors:
    output: true
    
defaults:
  - scope:
      path: ""
      type: documents
    values:
      layout: post
      author: marcanuy
  - scope:
      path: ""
      type: editors
    values:
      layout: editor
      
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-toc
  
#jekyll-seo-plugin (and footer)
twitter:
  username: emacside #The site's Twitter handle.


